//! Claude Code adapter (microplano 011).

use dare_assets::{
    load_capability_matrix_from_str, render_claude_command, sha256_hex, validate_capability_matrix,
    EmbeddedAssets,
};
use dare_core::fs::{atomic_write, read_to_string};
use dare_core::{CoreError, CoreResult, ProjectRoot, SafeRelativePath};
use serde_json::{json, Value};

const MANAGED_PREFIX: &str = "<!-- dare:managed";
const CLAUDE_MD_REL: &str = "CLAUDE.md";
const SETTINGS_REL: &str = ".claude/settings.json";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClaudeDetect {
    pub claude_md: bool,
    pub claude_dir: bool,
}

fn exists(root: &ProjectRoot, rel: &str) -> CoreResult<bool> {
    let path = SafeRelativePath::new(rel)?;
    Ok(root.resolve(&path)?.as_path().exists())
}

pub fn detect_claude(root: &ProjectRoot) -> CoreResult<ClaudeDetect> {
    Ok(ClaudeDetect {
        claude_md: exists(root, CLAUDE_MD_REL)?,
        claude_dir: exists(root, ".claude")?,
    })
}

fn should_write(root: &ProjectRoot, rel: &SafeRelativePath, force: bool) -> CoreResult<bool> {
    if force {
        return Ok(true);
    }
    let abs = root.resolve(rel)?;
    if !abs.as_path().exists() {
        return Ok(true);
    }
    let existing = read_to_string(root, rel)?;
    Ok(crate::content_is_managed(existing.as_bytes()))
}

fn load_matrix() -> CoreResult<dare_assets::CapabilityMatrix> {
    let file = EmbeddedAssets::get("capability-matrix.yml")
        .ok_or_else(|| CoreError::config("asset missing: capability-matrix.yml"))?;
    let yaml = std::str::from_utf8(file.data.as_ref())
        .map_err(|e| CoreError::config(format!("invalid capability-matrix encoding: {e}")))?;
    let matrix = load_capability_matrix_from_str(yaml)?;
    validate_capability_matrix(&matrix)?;
    Ok(matrix)
}

/// Generate a managed CLAUDE.md from a minimal DARE stub (idempotent).
pub fn generate_claude_md(root: &ProjectRoot, force: bool) -> CoreResult<()> {
    let rel = SafeRelativePath::new(CLAUDE_MD_REL)?;
    if !should_write(root, &rel, force)? {
        return Ok(());
    }
    let body = format!(
        "{MANAGED_PREFIX} claude-md -->\n# DARE Framework\n\n\
         Generated by `dare harness claude`. Follow Design → Blueprint → Tasks → Execute.\n\
         Use slash commands from `.claude/commands/`.\n"
    );
    atomic_write(root, &rel, body.as_bytes())
}

/// Install `.claude/commands/*.md` from the capability matrix.
/// Returns number of files written (skipped preserved files are not counted).
pub fn install_commands(root: &ProjectRoot, force: bool) -> CoreResult<usize> {
    let matrix = load_matrix()?;
    let mut written = 0usize;
    for cap in &matrix.capabilities {
        let Some(out) = cap.outputs.claude.as_deref() else {
            continue;
        };
        let rel = SafeRelativePath::new(out)?;
        if !should_write(root, &rel, force)? {
            continue;
        }
        let rendered = render_claude_command(cap);
        let body = format!("{MANAGED_PREFIX} capability={} -->\n{rendered}", cap.id);
        atomic_write(root, &rel, body.as_bytes())?;
        written += 1;
    }
    Ok(written)
}

fn default_settings() -> Value {
    json!({
        "permissions": {
            "allow": [
                "Bash(git:*)",
                "Read(DARE/**)",
                "Write(DARE/**)"
            ]
        },
        "hooks": {
            "PostToolUse": [{
                "matcher": "Write",
                "hooks": [{
                    "type": "command",
                    "command": "echo \"File saved. Remember Ralph Loop: cargo test --workspace && cargo clippy --all-features -- -D warnings\""
                }]
            }]
        }
    })
}

pub fn write_settings_json(root: &ProjectRoot, force: bool) -> CoreResult<()> {
    let rel = SafeRelativePath::new(SETTINGS_REL)?;
    let abs = root.resolve(&rel)?;
    if abs.as_path().exists() && !force {
        let existing = read_to_string(root, &rel)?;
        if !existing.contains("\"_dare_managed\"") {
            // preserve unmanaged custom settings
            return Ok(());
        }
    }
    let mut v = default_settings();
    if let Some(obj) = v.as_object_mut() {
        obj.insert("_dare_managed".into(), json!(true));
    }
    let bytes = serde_json::to_vec_pretty(&v).map_err(|e| CoreError::config(e.to_string()))?;
    atomic_write(root, &rel, &bytes)
}

/// Validate that every matrix claude output path exists under root.
pub fn validate_install(root: &ProjectRoot) -> CoreResult<usize> {
    let matrix = load_matrix()?;
    let mut ok = 0usize;
    let mut missing = Vec::new();
    for cap in &matrix.capabilities {
        let Some(out) = cap.outputs.claude.as_deref() else {
            continue;
        };
        let rel = SafeRelativePath::new(out)?;
        let abs = root.resolve(&rel)?;
        if abs.as_path().is_file() {
            ok += 1;
        } else {
            missing.push(out.to_string());
        }
    }
    if !missing.is_empty() {
        return Err(CoreError::config(format!(
            "claude commands missing ({}): {}",
            missing.len(),
            missing.into_iter().take(5).collect::<Vec<_>>().join(", ")
        )));
    }
    let _ = sha256_hex(b"ok");
    Ok(ok)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn detect_empty_and_generate_managed() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let d = detect_claude(&root).unwrap();
        assert!(!d.claude_md);
        assert!(!d.claude_dir);
        generate_claude_md(&root, false).unwrap();
        let d2 = detect_claude(&root).unwrap();
        assert!(d2.claude_md);
        let content =
            read_to_string(&root, &SafeRelativePath::new(CLAUDE_MD_REL).unwrap()).unwrap();
        assert!(content.starts_with(MANAGED_PREFIX));
        assert!(content.contains("dare harness claude"));
        assert!(content.contains(".claude/commands/"));
    }

    #[test]
    fn preserve_unmanaged_claude_md() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let rel = SafeRelativePath::new(CLAUDE_MD_REL).unwrap();
        atomic_write(&root, &rel, b"# my custom CLAUDE.md\nkeep me\n").unwrap();
        generate_claude_md(&root, false).unwrap();
        let content = read_to_string(&root, &rel).unwrap();
        assert!(content.contains("my custom CLAUDE.md"));
        assert!(!content.starts_with(MANAGED_PREFIX));
    }

    #[test]
    fn install_validate_roundtrip_force() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        assert!(!detect_claude(&root).unwrap().claude_md);
        generate_claude_md(&root, true).unwrap();
        let n = install_commands(&root, true).unwrap();
        assert_eq!(n, 50);
        write_settings_json(&root, true).unwrap();
        assert_eq!(validate_install(&root).unwrap(), 50);
        // preserve: second install without force should write 0 if all managed
        let n2 = install_commands(&root, false).unwrap();
        assert_eq!(n2, 50); // managed files are rewritten (idempotent)
    }

    #[test]
    fn preserve_unmanaged_command() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let rel = SafeRelativePath::new(".claude/commands/dare-design.md").unwrap();
        atomic_write(&root, &rel, b"# custom user command\n").unwrap();
        let n = install_commands(&root, false).unwrap();
        // 48 written (one preserved)
        assert_eq!(n, 48);
        let content = read_to_string(&root, &rel).unwrap();
        assert!(content.contains("custom user command"));
    }

    #[test]
    fn validate_reports_missing_sample() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let err = validate_install(&root).unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("claude commands missing"));
        assert!(msg.contains("(50):") || msg.contains("missing (50)"));
    }

    #[test]
    fn settings_managed_and_post_tool_use() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        write_settings_json(&root, true).unwrap();
        let rel = SafeRelativePath::new(SETTINGS_REL).unwrap();
        let raw = read_to_string(&root, &rel).unwrap();
        let v: Value = serde_json::from_str(&raw).unwrap();
        assert_eq!(v.get("_dare_managed"), Some(&json!(true)));
        let hooks = &v["hooks"]["PostToolUse"][0];
        assert_eq!(hooks["matcher"], "Write");
        assert_eq!(hooks["hooks"][0]["type"], "command");
        let cmd = hooks["hooks"][0]["command"].as_str().unwrap();
        assert!(cmd.contains("Ralph Loop"));
        assert!(cmd.contains("cargo test --workspace"));
    }

    #[test]
    fn preserve_unmanaged_settings() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let rel = SafeRelativePath::new(SETTINGS_REL).unwrap();
        atomic_write(&root, &rel, b"{\"custom\":true}\n").unwrap();
        write_settings_json(&root, false).unwrap();
        let content = read_to_string(&root, &rel).unwrap();
        assert!(content.contains("\"custom\":true"));
        assert!(!content.contains("_dare_managed"));
    }
}
