[workspace]
resolver = "2"
members = [
    "crates/dare-cli",
    "crates/dare-core",
    "crates/dare-contracts",
    "crates/dare-config",
    "crates/dare-assets",
]

[workspace.package]
version = "0.1.0-alpha.0"
edition = "2021"
rust-version = "1.85.0"
license = "Apache-2.0"

[workspace.dependencies]
clap = { version = "=4.5.40", features = ["derive"] }
thiserror = "=2.0.12"
anyhow = "=1.0.104"
tracing = "=0.1.44"
tracing-subscriber = { version = "=0.3.23", features = ["env-filter"] }
assert_cmd = "=2.0.17"
predicates = "=3.1.3"
serde_json = "=1.0.140"
serde = { version = "=1.0.219", features = ["derive"] }
uuid = { version = "=1.16.0", features = ["v4"] }
anstream = "=0.6.18"
camino = "=1.1.9"
tempfile = "=3.20.0"
fs4 = "=1.1.0"
sha2 = "=0.10.9"
kill_tree = "=0.2.4"
serde_yaml = { package = "yaml_serde", version = "=0.10.4" }
rust-embed = "=8.7.2"
dare-core = { path = "crates/dare-core" }
dare-contracts = { path = "crates/dare-contracts" }
dare-config = { path = "crates/dare-config" }
dare-assets = { path = "crates/dare-assets" }

[workspace.lints.rust]
unused = "warn"
dead_code = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
