//! Top-level CLI command modules.

pub mod ai;
pub mod bench;
pub mod bootstrap;
pub mod blueprint;
pub mod dag;
pub mod dashboard;
pub mod design;
pub mod discover;
pub mod dna;
pub mod execute;
pub mod execute_agent;
pub mod graph;
pub mod guard;
pub mod hooks;
pub mod info;
pub mod init;
mod init_prompts;
pub mod mcp;
pub mod migrate;
pub mod path_resolve;
pub mod patterns;
pub mod refine;
pub mod reverse;
pub mod review;
pub mod server;
pub mod skill;
pub mod steering;
pub mod update;
pub mod validate;
pub mod welcome;
