use dare_core::CoreResult;
use serde_json::json;

use crate::provider::{AiProvider, ProviderId};
use crate::request::{EnrichRaw, EnrichRequest};

const MOCK_OBJECTIVES: &str = "| # | Objetivo | Métrica verificável | Meta |\n|---|----------|---------------------|------|\n| O-01 | Generated by mock | | |";

const MOCK_FUNCTIONAL_REQUIREMENTS: &str = "| ID | Requisito | Prioridade | Critério de aceite |\n|----|-----------|------------|--------------------|\n| RF-01 | Generated by mock | MUST | stub |";

const MOCK_STACK: &str =
    "| Camada | Tecnologia | Versão |\n|--------|-----------|--------|\n| Runtime | mock | 0 |";

pub struct MockProvider;

impl AiProvider for MockProvider {
    fn id(&self) -> ProviderId {
        ProviderId::Mock
    }

    fn enrich(&self, req: &EnrichRequest) -> CoreResult<EnrichRaw> {
        if std::env::var("DARE_AI_MOCK_MODE").as_deref() == Ok("invalid-json") {
            return Ok(EnrichRaw {
                stdout: "{ not valid json".into(),
                stderr_redacted: String::new(),
                exit_code: 0,
            });
        }

        let stdout = if req.command == "blueprint" {
            json!({
                "sections": {
                    "architecture-overview": format!("Generated by mock — {}", req.title),
                    "execution-phases": "#### Fase 1: mock execution phase\n**Task:** `task-001`\n",
                    "api-contracts": "REST endpoints generated by mock for blueprint enrichment.",
                    "data-model": "| Entity | Fields |\n|--------|--------|\n| Widget | id, name |",
                }
            })
            .to_string()
        } else {
            json!({
                "sections": {
                    "description": req.description,
                    "objectives": MOCK_OBJECTIVES,
                    "functional-requirements": MOCK_FUNCTIONAL_REQUIREMENTS,
                    "stack": MOCK_STACK,
                }
            })
            .to_string()
        };

        Ok(EnrichRaw {
            stdout,
            stderr_redacted: String::new(),
            exit_code: 0,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse_and_validate_sections;

    fn sample_request(description: &str) -> EnrichRequest {
        EnrichRequest {
            command: "design".into(),
            title: "Sample".into(),
            description: description.into(),
            current_markdown: String::new(),
            cwd: None,
        }
    }

    #[test]
    fn mock_enrich_deterministic() {
        let provider = MockProvider;
        let req = sample_request("API de pagamentos com Stripe");

        let raw1 = provider.enrich(&req).unwrap();
        let raw2 = provider.enrich(&req).unwrap();

        assert_eq!(raw1, raw2);
        assert_eq!(raw1.exit_code, 0);
        assert!(raw1.stderr_redacted.is_empty());

        let sections1 = parse_and_validate_sections(&raw1.stdout).unwrap();
        let sections2 = parse_and_validate_sections(&raw2.stdout).unwrap();

        assert_eq!(sections1, sections2);
        assert_eq!(sections1["description"], "API de pagamentos com Stripe");
        assert_eq!(provider.id(), ProviderId::Mock);
    }
}
