//! Apply update plan: keep/replace/create with session journal (BLUEPRINT-022 §5.5–5.6).
//!
//! Config migrate for `dare.config.json` uses in-memory `dare-config` + session backup
//! (never nested `apply_migrate` / `.dare/backups`).

use dare_assets::EmbeddedAssets;
use dare_config::{apply_plan_in_memory, default_config, plan_migrate, MigrateOptions};
use dare_contracts::{load_dare_config, save_dare_config, DareConfig};
use dare_core::fs::atomic_write;
use dare_core::{CoreError, CoreResult, ProjectRoot, SafeRelativePath};
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::classify::AssetUpdateStatus;
use crate::load_desired_manifest_v2_embedded;
use crate::plan::{UpdateItem, UpdatePlan};
use crate::policy::{resolve_action, ApplyAction, ApplyOptions, AskContext};
use crate::session_backup::{
    ensure_backup_root, ensure_parent_dirs, rollback_session, session_backup_file, SessionJournal,
};
use crate::UPDATE_APPLY_SCHEMA_VERSION;

const CONFIG_PATH: &str = "dare.config.json";

/// Apply mode string frozen in UpdateApplyReport schema 1.
pub const MODE_UPDATE: &str = "update";

/// Successful apply report (schemaVersion 1, camelCase JSON).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct UpdateApplyReport {
    pub schema_version: u32,
    pub mode: String,
    pub cli_version: String,
    pub project_root: String,
    pub backup_root: Option<String>,
    pub target: Option<String>,
    pub force: bool,
    pub yes: bool,
    pub kept: Vec<String>,
    pub created: Vec<String>,
    pub replaced: Vec<String>,
    pub skipped: Vec<String>,
    pub backed_up: Vec<String>,
    pub migrated: Vec<String>,
    pub warnings: Vec<String>,
    pub rolled_back: bool,
}

/// Load canonical bytes for a plan item from the embedded V2 inventory / rust-embed.
///
/// Resolution order:
/// 1. Embedded V2 asset matching `item.path` → `source` if set, else `path`
/// 2. Direct `EmbeddedAssets::get(item.path)` (templates / canonical files)
/// 3. Harness generators (CLAUDE.md, AGENTS.md, .cursorrules, .antigravityrules)
fn canonical_bytes_for(item: &UpdateItem) -> CoreResult<Vec<u8>> {
    if let Ok(manifest) = load_desired_manifest_v2_embedded() {
        if let Some(asset) = manifest.assets.iter().find(|a| a.path == item.path) {
            let key = asset.source.as_deref().unwrap_or(asset.path.as_str());
            if let Some(file) = EmbeddedAssets::get(key) {
                return Ok(file.data.as_ref().to_vec());
            }
        }
    }
    if let Some(file) = EmbeddedAssets::get(&item.path) {
        return Ok(file.data.as_ref().to_vec());
    }
    if let Some(bytes) = harness_canonical_bytes(&item.path)? {
        return Ok(bytes);
    }
    Err(CoreError::not_found(format!(
        "canonical embedded asset missing for path: {}",
        item.path
    )))
}

const MANAGED_PREFIX: &str = "<!-- dare:managed";

/// Canonical harness file bodies (mirrors `dare_harness` generators; no disk write).
fn harness_canonical_bytes(path: &str) -> CoreResult<Option<Vec<u8>>> {
    Ok(Some(match path {
        "CLAUDE.md" => format!(
            "{MANAGED_PREFIX} claude-md -->\n# DARE Framework\n\n\
             Generated by `dare harness claude`. Follow Design → Blueprint → Tasks → Execute.\n\
             Use slash commands from `.claude/commands/`.\n"
        )
        .into_bytes(),
        ".cursorrules" => format!(
            "{MANAGED_PREFIX} cursorrules -->\n# DARE Cursor rules\n\n\
             Follow DARE Design → Blueprint → Tasks → Execute. Prefer slash commands.\n"
        )
        .into_bytes(),
        ".antigravityrules" => format!(
            "{MANAGED_PREFIX} antigravityrules -->\n# DARE Antigravity rules\n\n\
             Follow Design → Blueprint → Tasks → Execute. Use Agent Skills under `.agents/skills/`.\n\
             Shared with Codex — do not diverge skill bodies.\n"
        )
        .into_bytes(),
        "AGENTS.md" => agents_md_canonical_bytes()?,
        _ => return Ok(None),
    }))
}

fn agents_md_canonical_bytes() -> CoreResult<Vec<u8>> {
    use dare_assets::{load_capability_matrix_from_str, validate_capability_matrix};

    let file = EmbeddedAssets::get("capability-matrix.yml")
        .ok_or_else(|| CoreError::config("asset missing: capability-matrix.yml"))?;
    let yaml = std::str::from_utf8(file.data.as_ref())
        .map_err(|e| CoreError::config(format!("invalid capability-matrix encoding: {e}")))?;
    let matrix = load_capability_matrix_from_str(yaml)?;
    validate_capability_matrix(&matrix)?;

    let mut lines = vec![
        format!("{MANAGED_PREFIX} agents-md -->"),
        "# DARE Codex Agents".into(),
        String::new(),
        "Invoke Agent Skills with `$skill-name` (example: `$dare-design`).".into(),
        String::new(),
        "## Skills".into(),
    ];
    for cap in &matrix.capabilities {
        if cap.outputs.codex.is_none() {
            continue;
        }
        lines.push(format!("- `${}` — {}", cap.id, cap.description.trim()));
    }
    lines.push(String::new());
    lines.push(
        "Shared skills live under `.agents/skills/` (Antigravity coexistence) and `.codex/skills/`."
            .into(),
    );
    lines.push(String::new());
    Ok(lines.join("\n").into_bytes())
}

/// Whether the apply session should migrate `dare.config.json`.
///
/// True when any plan item for the config has status ∈ {Missing, Apply}, or
/// (Customized && resolved action is Replace). Customized + Keep → false.
fn should_migrate(plan: &UpdatePlan, opts: &ApplyOptions, batch_replace: bool) -> bool {
    for item in &plan.items {
        if item.path != CONFIG_PATH {
            continue;
        }
        match item.status {
            AssetUpdateStatus::Missing | AssetUpdateStatus::Apply => return true,
            AssetUpdateStatus::Customized => {
                return resolve_action(item.status, opts, batch_replace) == ApplyAction::Replace;
            }
            AssetUpdateStatus::Identical => return false,
        }
    }
    false
}

fn load_config_or_default(
    root: &ProjectRoot,
    rel: &SafeRelativePath,
) -> CoreResult<(DareConfig, bool)> {
    match load_dare_config(root, rel) {
        Ok(cfg) => Ok((cfg, true)),
        Err(CoreError::NotFound(_)) => Ok((default_config(), false)),
        Err(e) => Err(e),
    }
}

#[cfg(test)]
struct Failpoint {
    after_n: usize,
    successful_writes: usize,
}

#[cfg(test)]
impl Failpoint {
    fn new(after_n: usize) -> Self {
        Self {
            after_n,
            successful_writes: 0,
        }
    }

    /// Call after each successful atomic write / replace / config save.
    fn after_successful_write(&mut self) -> CoreResult<()> {
        self.successful_writes += 1;
        if self.successful_writes >= self.after_n {
            return Err(CoreError::io(format!(
                "failpoint: simulated I/O failure after {} write(s)",
                self.after_n
            )));
        }
        Ok(())
    }
}

#[cfg(test)]
fn note_write(failpoint: &mut Option<Failpoint>) -> CoreResult<()> {
    if let Some(fp) = failpoint.as_mut() {
        return fp.after_successful_write();
    }
    Ok(())
}

#[cfg(not(test))]
fn note_write() -> CoreResult<()> {
    Ok(())
}

fn apply_update_inner(
    root: &ProjectRoot,
    plan: &UpdatePlan,
    mut opts: ApplyOptions,
    #[cfg(test)] mut failpoint: Option<Failpoint>,
) -> CoreResult<UpdateApplyReport> {
    let mut kept = Vec::new();
    let mut created = Vec::new();
    let mut replaced = Vec::new();
    let skipped: Vec<String> = Vec::new();
    let mut backed_up = Vec::new();
    let mut migrated = Vec::new();
    let mut warnings = Vec::new();

    let mut customized_paths: Vec<String> = plan
        .items
        .iter()
        .filter(|i| i.status == AssetUpdateStatus::Customized)
        .map(|i| i.path.clone())
        .collect();
    customized_paths.sort();

    let mut batch_replace = false;
    if !opts.force && opts.interactive {
        if let Some(ref mut ask) = opts.ask {
            batch_replace = ask(&AskContext {
                customized_paths: customized_paths.clone(),
            });
        }
    }

    let mut journal = SessionJournal::default();
    let mut backup_root: Option<SafeRelativePath> = None;
    let mut report_backup_root: Option<String> = None;

    let need_backup_root = |backup_root: &mut Option<SafeRelativePath>,
                            report_backup_root: &mut Option<String>,
                            journal: &mut SessionJournal,
                            opts: &ApplyOptions|
     -> CoreResult<SafeRelativePath> {
        if let Some(ref br) = backup_root {
            return Ok(br.clone());
        }
        let br = ensure_backup_root(root, &opts.cli_version)?;
        journal.backup_root = br.as_str().to_string();
        *report_backup_root = Some(br.as_str().to_string());
        *backup_root = Some(br.clone());
        Ok(br)
    };

    let mut apply_body = || -> CoreResult<()> {
        for item in &plan.items {
            let action = resolve_action(item.status, &opts, batch_replace);

            // Config: Keep is recorded here; Replace is deferred to the migrate step.
            if item.path == CONFIG_PATH {
                match action {
                    ApplyAction::Keep => {
                        kept.push(item.path.clone());
                        if item.status == AssetUpdateStatus::Customized && !opts.force {
                            warnings.push(format!("kept customized: {}", item.path));
                        }
                    }
                    ApplyAction::Replace => {
                        // Migrated in step below (no raw embedded replace).
                    }
                }
                continue;
            }

            match action {
                ApplyAction::Keep => {
                    kept.push(item.path.clone());
                    if item.status == AssetUpdateStatus::Customized && !opts.force {
                        warnings.push(format!("kept customized: {}", item.path));
                    }
                }
                ApplyAction::Replace => {
                    let bytes = canonical_bytes_for(item)?;
                    let dest = SafeRelativePath::new(&item.path)?;
                    let abs = root.resolve(&dest)?;
                    let existed = abs.as_path().is_file();

                    if existed {
                        let br = need_backup_root(
                            &mut backup_root,
                            &mut report_backup_root,
                            &mut journal,
                            &opts,
                        )?;
                        session_backup_file(root, &br, &item.path, &mut journal)?;
                        backed_up.push(item.path.clone());
                    }

                    ensure_parent_dirs(root, &dest, &mut journal)?;
                    atomic_write(root, &dest, &bytes)?;

                    if !existed {
                        journal.created.push(item.path.clone());
                        created.push(item.path.clone());
                    } else {
                        replaced.push(item.path.clone());
                    }

                    #[cfg(test)]
                    note_write(&mut failpoint)?;
                    #[cfg(not(test))]
                    note_write()?;
                }
            }
        }

        // Migrate step (BLUEPRINT-022 §5.5 step 8) — single session journal, no apply_migrate.
        if should_migrate(plan, &opts, batch_replace) {
            let rel = SafeRelativePath::new(CONFIG_PATH)?;
            let abs = root.resolve(&rel)?;
            let existed = abs.as_path().is_file();

            let br = need_backup_root(
                &mut backup_root,
                &mut report_backup_root,
                &mut journal,
                &opts,
            )?;
            if existed {
                session_backup_file(root, &br, CONFIG_PATH, &mut journal)?;
                backed_up.push(CONFIG_PATH.to_string());
            }

            let (cfg, _) = load_config_or_default(root, &rel)?;
            let migrate_opts = MigrateOptions {
                write_schema_version: true,
                schema_version: 1,
            };
            let plan_m = plan_migrate(&cfg, &migrate_opts);
            let after = apply_plan_in_memory(&cfg, &plan_m);
            save_dare_config(root, &rel, &after)?;

            if !existed {
                journal.created.push(CONFIG_PATH.to_string());
                created.push(CONFIG_PATH.to_string());
            } else {
                replaced.push(CONFIG_PATH.to_string());
            }
            migrated.push(CONFIG_PATH.to_string());

            #[cfg(test)]
            note_write(&mut failpoint)?;
            #[cfg(not(test))]
            note_write()?;
        }

        Ok(())
    };

    if let Err(e) = apply_body() {
        match rollback_session(root, &journal) {
            Ok(()) => return Err(e),
            Err(rb) => {
                return Err(CoreError::internal(format!(
                    "apply failed ({e}); rollback also failed ({rb})"
                )));
            }
        }
    }

    kept.sort();
    created.sort();
    replaced.sort();
    backed_up.sort();
    migrated.sort();
    warnings.sort();

    Ok(UpdateApplyReport {
        schema_version: UPDATE_APPLY_SCHEMA_VERSION,
        mode: MODE_UPDATE.to_string(),
        cli_version: opts.cli_version,
        project_root: root.to_posix(),
        backup_root: report_backup_root,
        target: plan.target.clone(),
        force: opts.force,
        yes: opts.yes,
        kept,
        created,
        replaced,
        skipped,
        backed_up,
        migrated,
        warnings,
        rolled_back: false,
    })
}

/// Apply an [`UpdatePlan`]: keep / replace / create with session backup + journal.
///
/// On any mid-loop error: attempts [`rollback_session`] then returns `Err`.
/// Migrates `dare.config.json` via in-memory plan when [`should_migrate`] is true.
pub fn apply_update(
    root: &ProjectRoot,
    plan: &UpdatePlan,
    opts: ApplyOptions,
) -> CoreResult<UpdateApplyReport> {
    #[cfg(test)]
    {
        apply_update_inner(root, plan, opts, None)
    }
    #[cfg(not(test))]
    {
        apply_update_inner(root, plan, opts)
    }
}

/// Like [`apply_update`], but after `after_n` successful writes returns `CoreError::Io`
/// so callers can assert session rollback.
#[cfg(test)]
pub(crate) fn apply_update_with_failpoint(
    root: &ProjectRoot,
    plan: &UpdatePlan,
    opts: ApplyOptions,
    after_n: usize,
) -> CoreResult<UpdateApplyReport> {
    apply_update_inner(root, plan, opts, Some(Failpoint::new(after_n)))
}

/// Human-readable apply report (en-US). Final line MUST be `mode: update`.
pub fn format_apply_human(r: &UpdateApplyReport) -> String {
    let target = r.target.as_deref().unwrap_or("(all)");
    let backup = r.backup_root.as_deref().unwrap_or("(none)");
    let mut out = String::new();
    out.push_str("update: apply\n");
    out.push_str(&format!("cliVersion: {}\n", r.cli_version));
    out.push_str(&format!("projectRoot: {}\n", r.project_root));
    out.push_str(&format!("backupRoot: {backup}\n"));
    out.push_str(&format!("target: {target}\n"));
    out.push_str(&format!(
        "counts: kept={} created={} replaced={} backedUp={} migrated={}\n",
        r.kept.len(),
        r.created.len(),
        r.replaced.len(),
        r.backed_up.len(),
        r.migrated.len()
    ));
    if !r.warnings.is_empty() {
        out.push_str("warnings:\n");
        for w in &r.warnings {
            out.push_str(&format!("  - {w}\n"));
        }
    }
    out.push_str("mode: update\n");
    out
}

/// Serialize an [`UpdateApplyReport`] to camelCase JSON [`Value`].
pub fn apply_report_to_json(r: &UpdateApplyReport) -> CoreResult<Value> {
    serde_json::to_value(r)
        .map_err(|e| CoreError::config(format!("failed to serialize UpdateApplyReport: {e}")))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::plan::{UpdateCounts, UpdateItem, MODE_DRY_RUN};
    use crate::UPDATE_PLAN_SCHEMA_VERSION;
    use dare_assets::sha256_hex;
    use dare_core::ErrorKind;
    use serde_json::json;
    use std::fs;
    use tempfile::tempdir;

    const TEMPLATE_PATH: &str = "templates/DESIGN-template.md";
    const TEMPLATE_B_PATH: &str = "templates/BLUEPRINT-template.md";

    fn canonical_template() -> Vec<u8> {
        EmbeddedAssets::get(TEMPLATE_PATH)
            .expect("embedded DESIGN template")
            .data
            .as_ref()
            .to_vec()
    }

    fn canonical_template_b() -> Vec<u8> {
        EmbeddedAssets::get(TEMPLATE_B_PATH)
            .expect("embedded BLUEPRINT template")
            .data
            .as_ref()
            .to_vec()
    }

    fn opts(yes: bool, force: bool) -> ApplyOptions {
        ApplyOptions {
            yes,
            force,
            interactive: false,
            ask: None,
            cli_version: "0.1.0-alpha.0".into(),
        }
    }

    fn item(path: &str, status: AssetUpdateStatus, expected: &str) -> UpdateItem {
        UpdateItem {
            path: path.into(),
            status,
            expected_sha256: expected.into(),
            actual_sha256: None,
            applies_to: vec!["*".into()],
        }
    }

    fn plan_with(items: Vec<UpdateItem>) -> UpdatePlan {
        UpdatePlan {
            schema_version: UPDATE_PLAN_SCHEMA_VERSION,
            mode: MODE_DRY_RUN.into(),
            project_root: "/tmp".into(),
            target: None,
            cli_version: "0.1.0-alpha.0".into(),
            counts: UpdateCounts::default(),
            items,
        }
    }

    #[test]
    fn apply_keeps_customized_with_yes() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let custom = b"# my customized template\n";
        let rel = SafeRelativePath::new(TEMPLATE_PATH).unwrap();
        atomic_write(&root, &rel, custom).unwrap();

        let expected = sha256_hex(&canonical_template());
        let plan = plan_with(vec![item(
            TEMPLATE_PATH,
            AssetUpdateStatus::Customized,
            &expected,
        )]);
        let report = apply_update(&root, &plan, opts(true, false)).unwrap();

        assert_eq!(fs::read(dir.path().join(TEMPLATE_PATH)).unwrap(), custom);
        assert!(report.kept.iter().any(|p| p == TEMPLATE_PATH));
        assert!(report
            .warnings
            .iter()
            .any(|w| w.contains("kept customized")));
        assert!(report.replaced.is_empty());
        assert!(report.backup_root.is_none());
        assert!(!report.rolled_back);
    }

    #[test]
    fn apply_force_replaces_customized() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let custom = b"# customized - will be replaced\n";
        let rel = SafeRelativePath::new(TEMPLATE_PATH).unwrap();
        atomic_write(&root, &rel, custom).unwrap();

        let canon = canonical_template();
        let expected = sha256_hex(&canon);
        let plan = plan_with(vec![item(
            TEMPLATE_PATH,
            AssetUpdateStatus::Customized,
            &expected,
        )]);
        let report = apply_update(&root, &plan, opts(false, true)).unwrap();

        assert_eq!(fs::read(dir.path().join(TEMPLATE_PATH)).unwrap(), canon);
        assert!(report.replaced.iter().any(|p| p == TEMPLATE_PATH));
        assert!(report.backed_up.iter().any(|p| p == TEMPLATE_PATH));
        assert!(report.backup_root.is_some());
        let bak = report.backup_root.as_ref().unwrap();
        assert!(dir.path().join(bak).join(TEMPLATE_PATH).is_file());
    }

    #[test]
    fn apply_creates_missing() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let canon = canonical_template();
        let expected = sha256_hex(&canon);
        let plan = plan_with(vec![item(
            TEMPLATE_PATH,
            AssetUpdateStatus::Missing,
            &expected,
        )]);
        let report = apply_update(&root, &plan, opts(true, false)).unwrap();

        assert_eq!(fs::read(dir.path().join(TEMPLATE_PATH)).unwrap(), canon);
        assert_eq!(report.created, vec![TEMPLATE_PATH.to_string()]);
        assert!(report.replaced.is_empty());
        assert!(report.backup_root.is_none());
    }

    #[test]
    fn apply_identical_noop() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let canon = canonical_template();
        let rel = SafeRelativePath::new(TEMPLATE_PATH).unwrap();
        atomic_write(&root, &rel, &canon).unwrap();

        let before: Vec<_> = walkdir_files(dir.path());
        let expected = sha256_hex(&canon);
        let plan = plan_with(vec![item(
            TEMPLATE_PATH,
            AssetUpdateStatus::Identical,
            &expected,
        )]);
        let report = apply_update(&root, &plan, opts(false, false)).unwrap();

        let after: Vec<_> = walkdir_files(dir.path());
        assert_eq!(before, after);
        assert_eq!(report.kept, vec![TEMPLATE_PATH.to_string()]);
        assert!(report.created.is_empty());
        assert!(report.replaced.is_empty());
        assert!(report.backup_root.is_none());
        assert!(report.backed_up.is_empty());
    }

    #[test]
    fn report_schema_version_1_sorted_lists() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();

        // Create z-path as customized (force replace), leave a-path missing (create).
        // Plan items intentionally reverse-sorted; report lists must be sorted.
        let custom = b"custom-blueprint\n";
        atomic_write(
            &root,
            &SafeRelativePath::new(TEMPLATE_B_PATH).unwrap(),
            custom,
        )
        .unwrap();

        let plan = plan_with(vec![
            item(
                TEMPLATE_B_PATH,
                AssetUpdateStatus::Customized,
                &sha256_hex(&canonical_template_b()),
            ),
            item(
                TEMPLATE_PATH,
                AssetUpdateStatus::Missing,
                &sha256_hex(&canonical_template()),
            ),
        ]);
        let report = apply_update(&root, &plan, opts(false, true)).unwrap();
        let v = apply_report_to_json(&report).unwrap();

        assert_eq!(v["schemaVersion"], 1);
        assert_eq!(v["mode"], "update");
        assert!(v.get("schema_version").is_none());
        assert_eq!(v["rolledBack"], false);

        let created = v["created"].as_array().unwrap();
        let replaced = v["replaced"].as_array().unwrap();
        assert!(is_sorted_json_strs(created));
        assert!(is_sorted_json_strs(replaced));
        assert_eq!(
            created
                .iter()
                .map(|x| x.as_str().unwrap())
                .collect::<Vec<_>>(),
            vec![TEMPLATE_PATH]
        );
        assert_eq!(
            replaced
                .iter()
                .map(|x| x.as_str().unwrap())
                .collect::<Vec<_>>(),
            vec![TEMPLATE_B_PATH]
        );

        let human = format_apply_human(&report);
        assert!(
            human.lines().last() == Some("mode: update")
                || human.trim_end().ends_with("mode: update"),
            "human must end with mode: update, got:\n{human}"
        );
    }

    #[test]
    fn apply_migrate_writes_schema_version() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let raw = r#"{"ide":"cursor","customExtension":{"x":1}}"#;
        fs::write(dir.path().join(CONFIG_PATH), raw).unwrap();

        let plan = plan_with(vec![item(
            CONFIG_PATH,
            AssetUpdateStatus::Apply,
            "deadbeef",
        )]);
        let report = apply_update(&root, &plan, opts(true, false)).unwrap();

        assert!(report.migrated.iter().any(|p| p == CONFIG_PATH));
        assert!(report.replaced.iter().any(|p| p == CONFIG_PATH));
        assert!(report.backed_up.iter().any(|p| p == CONFIG_PATH));
        assert!(report.backup_root.is_some());

        let cfg = load_dare_config(&root, &SafeRelativePath::new(CONFIG_PATH).unwrap()).unwrap();
        assert_eq!(cfg.extra.get("schemaVersion"), Some(&json!(1)));
        assert_eq!(cfg.extra.get("customExtension"), Some(&json!({"x": 1})));
        assert_eq!(cfg.ide.as_deref(), Some("cursor"));

        // Session journal only — no nested .dare/backups from apply_migrate.
        assert!(!dir.path().join(".dare/backups").exists());
    }

    #[test]
    fn apply_migrate_kept_customized_config_skips() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let raw = r#"{"ide":"cursor","customExtension":{"x":1}}"#;
        let before = raw.as_bytes().to_vec();
        fs::write(dir.path().join(CONFIG_PATH), &before).unwrap();

        let plan = plan_with(vec![item(
            CONFIG_PATH,
            AssetUpdateStatus::Customized,
            "deadbeef",
        )]);
        let report = apply_update(&root, &plan, opts(true, false)).unwrap();

        assert!(report.migrated.is_empty());
        assert!(report.kept.iter().any(|p| p == CONFIG_PATH));
        assert!(report
            .warnings
            .iter()
            .any(|w| w.contains("kept customized")));
        assert_eq!(fs::read(dir.path().join(CONFIG_PATH)).unwrap(), before);

        let cfg = load_dare_config(&root, &SafeRelativePath::new(CONFIG_PATH).unwrap()).unwrap();
        assert!(!cfg.extra.contains_key("schemaVersion"));
        assert!(report.backup_root.is_none());
    }

    #[test]
    fn apply_partial_failure_rolls_back() {
        let dir = tempdir().unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();

        // Pre-existing customized file that force will replace (first write),
        // plus a missing template (second write — failpoint trips after write #1).
        let custom = b"# keep-me-via-rollback\n";
        atomic_write(
            &root,
            &SafeRelativePath::new(TEMPLATE_PATH).unwrap(),
            custom,
        )
        .unwrap();

        let before_content = fs::read(dir.path().join(TEMPLATE_PATH)).unwrap();
        let before_files = asset_tree_excluding_backup(dir.path());

        let plan = plan_with(vec![
            item(
                TEMPLATE_PATH,
                AssetUpdateStatus::Customized,
                &sha256_hex(&canonical_template()),
            ),
            item(
                TEMPLATE_B_PATH,
                AssetUpdateStatus::Missing,
                &sha256_hex(&canonical_template_b()),
            ),
        ]);

        let err = apply_update_with_failpoint(&root, &plan, opts(false, true), 1).unwrap_err();
        assert_eq!(err.kind(), ErrorKind::Io);

        assert_eq!(
            fs::read(dir.path().join(TEMPLATE_PATH)).unwrap(),
            before_content
        );
        assert!(!dir.path().join(TEMPLATE_B_PATH).exists());

        let after_files = asset_tree_excluding_backup(dir.path());
        assert_eq!(before_files, after_files);

        // Backup dir may remain for audit.
        let dare = dir.path().join(".dare");
        if dare.is_dir() {
            let has_backup = fs::read_dir(&dare)
                .unwrap()
                .flatten()
                .any(|e| e.file_name().to_string_lossy().starts_with("backup-"));
            assert!(has_backup, "expected session backup dir to remain");
        }
    }

    fn is_sorted_json_strs(arr: &[Value]) -> bool {
        let s: Vec<&str> = arr.iter().filter_map(|v| v.as_str()).collect();
        let mut t = s.clone();
        t.sort();
        s == t
    }

    fn walkdir_files(base: &std::path::Path) -> Vec<String> {
        let mut out = Vec::new();
        fn walk(base: &std::path::Path, cur: &std::path::Path, out: &mut Vec<String>) {
            let Ok(entries) = fs::read_dir(cur) else {
                return;
            };
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    walk(base, &path, out);
                } else if let Ok(rel) = path.strip_prefix(base) {
                    out.push(rel.to_string_lossy().replace('\\', "/"));
                }
            }
        }
        walk(base, base, &mut out);
        out.sort();
        out
    }

    /// Asset tree paths excluding session backup dirs under `.dare/backup-*`.
    fn asset_tree_excluding_backup(base: &std::path::Path) -> Vec<(String, Vec<u8>)> {
        let mut out = Vec::new();
        for rel in walkdir_files(base) {
            if rel.starts_with(".dare/backup-") {
                continue;
            }
            let bytes = fs::read(base.join(&rel)).unwrap_or_default();
            out.push((rel, bytes));
        }
        out
    }
}
