//! Idempotent brownfield install (`dare discover` without `--check`).

use std::path::{Path, PathBuf};

use dare_assets::EmbeddedAssets;
use dare_contracts::{load_dare_config, save_dare_config, save_graph, DareConfig, GraphDocument};
use dare_core::fs::{atomic_write, backup, read_to_string, restore};
use dare_core::{CoreError, CoreResult, ProjectRoot, SafeRelativePath};
use dare_harness::{
    ensure_workflows_dir, generate_agents_md, generate_antigravityrules, generate_claude_md,
    generate_cursorrules, install_antigravity, install_codex_skills, install_commands,
    install_cursor_commands, validate_antigravity_install, validate_codex_install,
    validate_cursor_install, validate_install, write_settings_json,
};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use crate::detect::detect;
use crate::report::{DetectionReport, StackConflict};

pub const INSTALL_SCHEMA_VERSION: u32 = 1;
pub const INSTALL_READ_CAP: usize = 262_144;
pub const GITIGNORE_BEGIN: &str = "# BEGIN DARE";
pub const GITIGNORE_END: &str = "# END DARE";
pub const GITIGNORE_LINES: &[&str] = &[".dare/", ".dare/backups/"];
pub const DARE_README_REL: &str = "DARE/README.md";
pub const GRAPH_REL: &str = "dare-graph.yml";
pub const CONFIG_REL: &str = "dare.config.json";

const STEP_IDS: &[&str] = &[
    "ensure_dirs",
    "write_config",
    "materialize_templates",
    "write_graph",
    "merge_gitignore",
    "install_harness_claude",
    "install_harness_cursor",
    "install_harness_codex",
    "install_harness_antigravity",
    "ensure_capability_discover",
    "validate_harnesses",
];

const TEMPLATE_ASSETS: &[&str] = &[
    "templates/DESIGN-template.md",
    "templates/BLUEPRINT-template.md",
    "templates/TASKS-template.md",
    "templates/TASK-SPEC-template.md",
    "templates/TELEMETRY-template.md",
    "templates/HOOKS-ADAPTER.md",
];

const DISCOVER_PATHS: &[&str] = &[
    ".claude/commands/dare-discover.md",
    ".cursor/commands/dare-discover.md",
    ".codex/skills/dare-discover/SKILL.md",
    ".antigravity/commands/dare-discover.md",
];

const README_BODY: &str =
    "# DARE\n\nMethodology artifacts live here. Generated by `dare discover`.\n";

#[derive(Debug, Clone, Default)]
pub struct InstallOptions {
    pub force: bool,
    pub dry_run: bool,
    pub strict_conflicts: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct StepResult {
    pub id: String,
    pub status: String,
    pub paths: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct InstallReport {
    pub schema_version: u32,
    pub mode: String,
    pub project_root: String,
    pub steps: Vec<StepResult>,
    pub created: Vec<String>,
    pub updated: Vec<String>,
    pub skipped: Vec<String>,
    pub backed_up: Vec<String>,
    pub harnesses_validated: Vec<String>,
    pub conflicts: Vec<StackConflict>,
    pub warnings: Vec<String>,
    pub dry_run: bool,
}

#[derive(Debug, Clone)]
pub struct InstallPlan {
    pub schema_version: u32,
    pub project_root: PathBuf,
    pub ide: String,
    pub steps: Vec<String>,
    pub warnings: Vec<String>,
    pub conflicts: Vec<StackConflict>,
}

#[derive(Debug, Default)]
struct SessionJournal {
    created_files: Vec<String>,
    created_dirs: Vec<String>,
    backups: Vec<(String, String)>,
}

/// Select `ide` value for `dare.config.json` (BLUEPRINT-019 §4.6).
pub fn select_ide(report: &DetectionReport) -> String {
    let present: Vec<&str> = report
        .harnesses
        .iter()
        .filter(|h| h.present)
        .map(|h| h.id.as_str())
        .collect();
    let has = |id: &str| present.contains(&id);
    let n = present.len();
    if n >= 3 {
        return "claude-code".to_string();
    }
    if has("cursor") && has("antigravity") && !has("claude") {
        return "hybrid".to_string();
    }
    if has("claude") && has("cursor") {
        return "claude-hybrid".to_string();
    }
    if n == 1 {
        return match present[0] {
            "claude" => "claude-code".to_string(),
            "cursor" => "cursor".to_string(),
            "codex" => "codex".to_string(),
            "antigravity" => "antigravity".to_string(),
            _ => "claude-code".to_string(),
        };
    }
    "claude-code".to_string()
}

/// Build an install plan (no filesystem writes).
pub fn plan_install(report: &DetectionReport, opts: &InstallOptions) -> CoreResult<InstallPlan> {
    let Some(root_s) = report.project_root.as_ref() else {
        return Err(CoreError::invalid_input(
            "project root not resolved; run from a project or use --check",
        ));
    };
    let project_root = PathBuf::from(root_s);
    if !project_root.is_dir() {
        return Err(CoreError::invalid_input(format!(
            "project root is not a directory: {root_s}"
        )));
    }

    if opts.strict_conflicts && !report.conflicts.is_empty() {
        return Err(CoreError::invalid_input(
            "stack conflicts present; re-run without --strict-conflicts or resolve manifests",
        ));
    }

    let mut warnings = Vec::new();
    if !report.conflicts.is_empty() {
        let kinds: Vec<String> = report
            .conflicts
            .iter()
            .flat_map(|c| c.kinds.clone())
            .collect();
        let mut kinds = kinds;
        kinds.sort();
        kinds.dedup();
        warnings.push(format!(
            "stack conflicts detected: {}; install continues",
            kinds.join(",")
        ));
    }
    warnings.sort();

    Ok(InstallPlan {
        schema_version: INSTALL_SCHEMA_VERSION,
        project_root,
        ide: select_ide(report),
        steps: STEP_IDS.iter().map(|s| (*s).to_string()).collect(),
        warnings,
        conflicts: report.conflicts.clone(),
    })
}

pub fn install_report_to_json(r: &InstallReport) -> Value {
    serde_json::to_value(r).unwrap_or(Value::Null)
}

pub fn format_install_human(r: &InstallReport) -> String {
    let mut out = String::new();
    out.push_str(&format!("schemaVersion: {}\n", r.schema_version));
    out.push_str(&format!("mode: {}\n", r.mode));
    out.push_str(&format!("projectRoot: {}\n", r.project_root));
    out.push_str(&format!("dryRun: {}\n", r.dry_run));
    if !r.warnings.is_empty() {
        out.push_str("warnings:\n");
        for w in &r.warnings {
            out.push_str(&format!("  - {w}\n"));
        }
    }
    if r.conflicts.is_empty() {
        out.push_str("conflicts: none\n");
    } else {
        out.push_str("conflicts:\n");
        for c in &r.conflicts {
            out.push_str(&format!("  - kinds={:?}\n", c.kinds));
        }
    }
    out.push_str(&format!(
        "created={} updated={} skipped={} backedUp={}\n",
        r.created.len(),
        r.updated.len(),
        r.skipped.len(),
        r.backed_up.len()
    ));
    out.push_str(&format!(
        "harnessesValidated: {:?}\n",
        r.harnesses_validated
    ));
    out.push_str("mode: install\n");
    out
}

fn empty_report(plan: &InstallPlan, dry_run: bool) -> InstallReport {
    let steps = plan
        .steps
        .iter()
        .map(|id| StepResult {
            id: id.clone(),
            status: "skipped".to_string(),
            paths: vec![],
        })
        .collect();
    InstallReport {
        schema_version: INSTALL_SCHEMA_VERSION,
        mode: "install".to_string(),
        project_root: plan.project_root.to_string_lossy().replace('\\', "/"),
        steps,
        created: vec![],
        updated: vec![],
        skipped: vec![],
        backed_up: vec![],
        harnesses_validated: vec![],
        conflicts: plan.conflicts.clone(),
        warnings: plan.warnings.clone(),
        dry_run,
    }
}

fn sort_unique(v: &mut Vec<String>) {
    v.sort();
    v.dedup();
}

fn path_exists(root: &ProjectRoot, rel: &str) -> CoreResult<bool> {
    let p = SafeRelativePath::new(rel)?;
    Ok(root.resolve(&p)?.as_path().exists())
}

fn ensure_dir(root: &ProjectRoot, rel: &str, journal: &mut SessionJournal) -> CoreResult<bool> {
    let p = SafeRelativePath::new(rel)?;
    let abs = root.resolve(&p)?;
    if abs.as_path().is_dir() {
        return Ok(false);
    }
    std::fs::create_dir_all(abs.as_path().as_std_path())
        .map_err(|e| CoreError::io(e.to_string()))?;
    journal.created_dirs.push(rel.to_string());
    Ok(true)
}

fn write_new_file(
    root: &ProjectRoot,
    rel: &str,
    data: &[u8],
    journal: &mut SessionJournal,
) -> CoreResult<()> {
    let p = SafeRelativePath::new(rel)?;
    atomic_write(root, &p, data)?;
    journal.created_files.push(rel.to_string());
    Ok(())
}

fn backup_if_exists(root: &ProjectRoot, rel: &str, journal: &mut SessionJournal) -> CoreResult<()> {
    let p = SafeRelativePath::new(rel)?;
    if !root.resolve(&p)?.as_path().is_file() {
        return Ok(());
    }
    let bak = backup(root, &p)?;
    journal
        .backups
        .push((rel.to_string(), bak.as_str().to_string()));
    Ok(())
}

fn rollback(root: &ProjectRoot, journal: &SessionJournal) -> CoreResult<()> {
    for (dest, bak) in journal.backups.iter().rev() {
        let dest_rel = SafeRelativePath::new(dest)?;
        let bak_rel = SafeRelativePath::new(bak)?;
        restore(root, &bak_rel, &dest_rel)
            .map_err(|e| CoreError::internal(format!("rollback restore failed for {dest}: {e}")))?;
    }
    for rel in journal.created_files.iter().rev() {
        let p = SafeRelativePath::new(rel)?;
        let abs = root.resolve(&p)?;
        if abs.as_path().is_file() {
            let _ = std::fs::remove_file(abs.as_path().as_std_path());
        }
    }
    for rel in journal.created_dirs.iter().rev() {
        let p = SafeRelativePath::new(rel)?;
        let abs = root.resolve(&p)?;
        if abs.as_path().is_dir() {
            let _ = std::fs::remove_dir(abs.as_path().as_std_path());
        }
    }
    Ok(())
}

fn merge_gitignore_content(existing: &str) -> String {
    let begin = GITIGNORE_BEGIN;
    let end = GITIGNORE_END;
    if let Some(start) = existing.find(begin) {
        if let Some(end_rel) = existing[start..].find(end) {
            let block_start = start;
            let block_end = start + end_rel + end.len();
            let before = &existing[..block_start];
            let after = &existing[block_end..];
            let inner = &existing[block_start + begin.len()..start + end_rel];
            let mut lines: Vec<String> = inner
                .lines()
                .map(|l| l.trim().to_string())
                .filter(|l| !l.is_empty())
                .collect();
            for req in GITIGNORE_LINES {
                if !lines.iter().any(|l| l == req) {
                    lines.push((*req).to_string());
                }
            }
            lines.sort();
            lines.dedup();
            let mut out = String::new();
            out.push_str(before.trim_end());
            if !before.is_empty() && !before.ends_with('\n') {
                out.push('\n');
            }
            out.push_str(begin);
            out.push('\n');
            for l in &lines {
                out.push_str(l);
                out.push('\n');
            }
            out.push_str(end);
            out.push('\n');
            out.push_str(after.trim_start_matches('\n'));
            if !out.ends_with('\n') {
                out.push('\n');
            }
            return out;
        }
    }
    let mut out = existing.trim_end().to_string();
    if !out.is_empty() {
        out.push('\n');
    }
    out.push_str(begin);
    out.push('\n');
    for l in GITIGNORE_LINES {
        out.push_str(l);
        out.push('\n');
    }
    out.push_str(end);
    out.push('\n');
    out
}

fn gitignore_already_complete(content: &str) -> bool {
    content.contains(GITIGNORE_BEGIN)
        && content.contains(GITIGNORE_END)
        && GITIGNORE_LINES.iter().all(|l| content.contains(l))
}

fn step_ensure_dirs(root: &ProjectRoot, journal: &mut SessionJournal) -> CoreResult<StepResult> {
    let mut created = false;
    for d in ["DARE", "DARE/EXECUTION", ".dare"] {
        if ensure_dir(root, d, journal)? {
            created = true;
        }
    }
    if !path_exists(root, DARE_README_REL)? {
        write_new_file(root, DARE_README_REL, README_BODY.as_bytes(), journal)?;
        created = true;
    }
    Ok(StepResult {
        id: "ensure_dirs".to_string(),
        status: if created { "created" } else { "skipped" }.to_string(),
        paths: vec![
            "DARE".to_string(),
            "DARE/EXECUTION".to_string(),
            ".dare".to_string(),
            DARE_README_REL.to_string(),
        ],
    })
}

struct PathAcc<'a> {
    created: &'a mut Vec<String>,
    updated: &'a mut Vec<String>,
    skipped: &'a mut Vec<String>,
    backed_up: &'a mut Vec<String>,
}

fn step_write_config(
    root: &ProjectRoot,
    plan: &InstallPlan,
    opts: &InstallOptions,
    journal: &mut SessionJournal,
    acc: &mut PathAcc<'_>,
) -> CoreResult<StepResult> {
    let rel = CONFIG_REL;
    let exists = path_exists(root, rel)?;
    if exists && !opts.force {
        acc.skipped.push(rel.to_string());
        return Ok(StepResult {
            id: "write_config".to_string(),
            status: "skipped".to_string(),
            paths: vec![rel.to_string()],
        });
    }
    let cfg = if exists {
        backup_if_exists(root, rel, journal)?;
        if let Some((_, bak)) = journal.backups.last() {
            acc.backed_up.push(bak.clone());
        }
        let p = SafeRelativePath::new(rel)?;
        let mut loaded = load_dare_config(root, &p).unwrap_or_default();
        if opts.force || loaded.ide.is_none() {
            loaded.ide = Some(plan.ide.clone());
        }
        loaded
    } else {
        DareConfig {
            ide: Some(plan.ide.clone()),
            ..DareConfig::default()
        }
    };
    let p = SafeRelativePath::new(rel)?;
    if !exists {
        save_dare_config(root, &p, &cfg)?;
        journal.created_files.push(rel.to_string());
        acc.created.push(rel.to_string());
        Ok(StepResult {
            id: "write_config".to_string(),
            status: "created".to_string(),
            paths: vec![rel.to_string()],
        })
    } else {
        save_dare_config(root, &p, &cfg)?;
        acc.updated.push(rel.to_string());
        Ok(StepResult {
            id: "write_config".to_string(),
            status: "updated".to_string(),
            paths: vec![rel.to_string()],
        })
    }
}

fn step_templates(
    root: &ProjectRoot,
    opts: &InstallOptions,
    journal: &mut SessionJournal,
    acc: &mut PathAcc<'_>,
) -> CoreResult<StepResult> {
    let mut any_created = false;
    let mut any_updated = false;
    let mut paths = Vec::new();
    for asset in TEMPLATE_ASSETS {
        let dest = *asset; // already templates/...
        paths.push(dest.to_string());
        let exists = path_exists(root, dest)?;
        if exists && !opts.force {
            acc.skipped.push(dest.to_string());
            continue;
        }
        let file = EmbeddedAssets::get(asset)
            .ok_or_else(|| CoreError::config(format!("embedded asset missing: {asset}")))?;
        if exists {
            backup_if_exists(root, dest, journal)?;
            if let Some((_, bak)) = journal.backups.last() {
                acc.backed_up.push(bak.clone());
            }
            let p = SafeRelativePath::new(dest)?;
            atomic_write(root, &p, file.data.as_ref())?;
            acc.updated.push(dest.to_string());
            any_updated = true;
        } else {
            write_new_file(root, dest, file.data.as_ref(), journal)?;
            acc.created.push(dest.to_string());
            any_created = true;
        }
    }
    let status = if any_created {
        "created"
    } else if any_updated {
        "updated"
    } else {
        "skipped"
    };
    Ok(StepResult {
        id: "materialize_templates".to_string(),
        status: status.to_string(),
        paths,
    })
}

fn step_graph(
    root: &ProjectRoot,
    journal: &mut SessionJournal,
    acc: &mut PathAcc<'_>,
) -> CoreResult<StepResult> {
    let rel = GRAPH_REL;
    if path_exists(root, rel)? {
        acc.skipped.push(rel.to_string());
        return Ok(StepResult {
            id: "write_graph".to_string(),
            status: "skipped".to_string(),
            paths: vec![rel.to_string()],
        });
    }
    let mut doc = GraphDocument::default();
    doc.extra.insert("backend".to_string(), json!("sqlite"));
    let p = SafeRelativePath::new(rel)?;
    save_graph(root, &p, &doc)?;
    journal.created_files.push(rel.to_string());
    acc.created.push(rel.to_string());
    Ok(StepResult {
        id: "write_graph".to_string(),
        status: "created".to_string(),
        paths: vec![rel.to_string()],
    })
}

fn step_gitignore(
    root: &ProjectRoot,
    journal: &mut SessionJournal,
    acc: &mut PathAcc<'_>,
) -> CoreResult<StepResult> {
    let rel = ".gitignore";
    let p = SafeRelativePath::new(rel)?;
    let exists = path_exists(root, rel)?;
    let existing = if exists {
        let raw = read_to_string(root, &p)?;
        if raw.len() > INSTALL_READ_CAP {
            return Err(CoreError::invalid_input(".gitignore exceeds read cap"));
        }
        raw
    } else {
        String::new()
    };
    if exists && gitignore_already_complete(&existing) {
        acc.skipped.push(rel.to_string());
        return Ok(StepResult {
            id: "merge_gitignore".to_string(),
            status: "skipped".to_string(),
            paths: vec![rel.to_string()],
        });
    }
    let merged = merge_gitignore_content(&existing);
    if exists {
        backup_if_exists(root, rel, journal)?;
        if let Some((_, bak)) = journal.backups.last() {
            acc.backed_up.push(bak.clone());
        }
        atomic_write(root, &p, merged.as_bytes())?;
        acc.updated.push(rel.to_string());
        Ok(StepResult {
            id: "merge_gitignore".to_string(),
            status: "updated".to_string(),
            paths: vec![rel.to_string()],
        })
    } else {
        write_new_file(root, rel, merged.as_bytes(), journal)?;
        acc.created.push(rel.to_string());
        Ok(StepResult {
            id: "merge_gitignore".to_string(),
            status: "created".to_string(),
            paths: vec![rel.to_string()],
        })
    }
}

fn step_harness_claude(root: &ProjectRoot, force: bool) -> CoreResult<StepResult> {
    generate_claude_md(root, force)?;
    let n = install_commands(root, force)?;
    write_settings_json(root, force)?;
    Ok(StepResult {
        id: "install_harness_claude".to_string(),
        status: if n > 0 { "updated" } else { "skipped" }.to_string(),
        paths: vec![".claude".to_string(), "CLAUDE.md".to_string()],
    })
}

fn step_harness_cursor(root: &ProjectRoot, force: bool) -> CoreResult<StepResult> {
    generate_cursorrules(root, force)?;
    let n = install_cursor_commands(root, force)?;
    Ok(StepResult {
        id: "install_harness_cursor".to_string(),
        status: if n > 0 { "updated" } else { "skipped" }.to_string(),
        paths: vec![".cursor".to_string(), ".cursorrules".to_string()],
    })
}

fn step_harness_codex(root: &ProjectRoot, force: bool) -> CoreResult<StepResult> {
    generate_agents_md(root, force)?;
    let n = install_codex_skills(root, force)?;
    Ok(StepResult {
        id: "install_harness_codex".to_string(),
        status: if n > 0 { "updated" } else { "skipped" }.to_string(),
        paths: vec!["AGENTS.md".to_string(), ".agents/skills".to_string()],
    })
}

fn step_harness_antigravity(root: &ProjectRoot, force: bool) -> CoreResult<StepResult> {
    generate_antigravityrules(root, force)?;
    ensure_workflows_dir(root, force)?;
    let n = install_antigravity(root, force)?;
    Ok(StepResult {
        id: "install_harness_antigravity".to_string(),
        status: if n > 0 { "updated" } else { "skipped" }.to_string(),
        paths: vec![
            ".antigravity".to_string(),
            ".antigravityrules".to_string(),
            ".agents".to_string(),
        ],
    })
}

fn step_ensure_capability(root: &ProjectRoot, force: bool) -> CoreResult<StepResult> {
    let mut missing = Vec::new();
    for p in DISCOVER_PATHS {
        if !path_exists(root, p)? {
            missing.push(*p);
        }
    }
    if missing.is_empty() {
        return Ok(StepResult {
            id: "ensure_capability_discover".to_string(),
            status: "skipped".to_string(),
            paths: DISCOVER_PATHS.iter().map(|s| (*s).to_string()).collect(),
        });
    }
    // Re-run installs to materialize matrix outputs (includes dare-discover).
    let _ = install_commands(root, force)?;
    let _ = install_cursor_commands(root, force)?;
    let _ = install_codex_skills(root, force)?;
    let _ = install_antigravity(root, force)?;
    for p in DISCOVER_PATHS {
        if !path_exists(root, p)? {
            return Err(CoreError::config(format!(
                "dare-discover capability missing after install: {p}"
            )));
        }
    }
    Ok(StepResult {
        id: "ensure_capability_discover".to_string(),
        status: "updated".to_string(),
        paths: DISCOVER_PATHS.iter().map(|s| (*s).to_string()).collect(),
    })
}

fn step_validate(root: &ProjectRoot) -> CoreResult<StepResult> {
    validate_install(root)?;
    validate_cursor_install(root)?;
    validate_codex_install(root)?;
    validate_antigravity_install(root)?;
    Ok(StepResult {
        id: "validate_harnesses".to_string(),
        status: "updated".to_string(),
        paths: vec![],
    })
}

/// Apply an install plan under `root`.
pub fn apply_install(
    root: &ProjectRoot,
    plan: &InstallPlan,
    opts: &InstallOptions,
) -> CoreResult<InstallReport> {
    if opts.dry_run {
        return Ok(empty_report(plan, true));
    }

    let mut journal = SessionJournal::default();
    let mut created = Vec::new();
    let mut updated = Vec::new();
    let mut skipped = Vec::new();
    let mut backed_up = Vec::new();
    let result = (|| -> CoreResult<(Vec<StepResult>, Vec<String>)> {
        let mut acc = PathAcc {
            created: &mut created,
            updated: &mut updated,
            skipped: &mut skipped,
            backed_up: &mut backed_up,
        };
        #[allow(clippy::vec_init_then_push)]
        let steps = {
            let mut steps = Vec::new();
            steps.push(step_ensure_dirs(root, &mut journal)?);
            steps.push(step_write_config(root, plan, opts, &mut journal, &mut acc)?);
            steps.push(step_templates(root, opts, &mut journal, &mut acc)?);
            steps.push(step_graph(root, &mut journal, &mut acc)?);
            steps.push(step_gitignore(root, &mut journal, &mut acc)?);
            steps.push(step_harness_claude(root, opts.force)?);
            steps.push(step_harness_cursor(root, opts.force)?);
            steps.push(step_harness_codex(root, opts.force)?);
            steps.push(step_harness_antigravity(root, opts.force)?);
            steps.push(step_ensure_capability(root, opts.force)?);
            steps.push(step_validate(root)?);
            steps
        };
        let harnesses_validated = vec![
            "antigravity".to_string(),
            "claude".to_string(),
            "codex".to_string(),
            "cursor".to_string(),
        ];
        Ok((steps, harnesses_validated))
    })();

    let (steps, harnesses_validated) = match result {
        Ok(v) => v,
        Err(e) => {
            let _ = rollback(root, &journal);
            return Err(e);
        }
    };
    sort_unique(&mut created);
    sort_unique(&mut updated);
    sort_unique(&mut skipped);
    sort_unique(&mut backed_up);

    Ok(InstallReport {
        schema_version: INSTALL_SCHEMA_VERSION,
        mode: "install".to_string(),
        project_root: plan.project_root.to_string_lossy().replace('\\', "/"),
        steps,
        created,
        updated,
        skipped,
        backed_up,
        harnesses_validated,
        conflicts: plan.conflicts.clone(),
        warnings: plan.warnings.clone(),
        dry_run: false,
    })
}

/// Detect → plan → apply.
pub fn install(start: &Path, opts: &InstallOptions) -> CoreResult<InstallReport> {
    if !start.exists() || !start.is_dir() {
        return Err(CoreError::not_found(format!(
            "directory not found: {}",
            start.display()
        )));
    }
    let detection = detect(start)?;
    let plan = plan_install(&detection, opts)?;
    let root = ProjectRoot::new(&plan.project_root)?;
    apply_install(&root, &plan, opts)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::harnesses::empty_harnesses;
    use crate::report::{HarnessHit, DETECTION_SCHEMA_VERSION};
    use std::fs;

    fn base_report(root: &Path) -> DetectionReport {
        DetectionReport {
            schema_version: DETECTION_SCHEMA_VERSION,
            mode: "check".to_string(),
            project_root: Some(root.to_string_lossy().replace('\\', "/")),
            git_root: None,
            stacks: vec![],
            conflicts: vec![],
            monorepo: false,
            monorepo_evidence: vec![],
            harnesses: empty_harnesses(),
            dare_already_present: false,
        }
    }

    #[test]
    fn select_ide_defaults_claude_code() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        let r = base_report(dir.path());
        assert_eq!(select_ide(&r), "claude-code");
    }

    #[test]
    fn select_ide_hybrid() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        let mut r = base_report(dir.path());
        r.harnesses = vec![
            HarnessHit {
                id: "antigravity".into(),
                present: true,
                evidence: vec![],
            },
            HarnessHit {
                id: "claude".into(),
                present: false,
                evidence: vec![],
            },
            HarnessHit {
                id: "codex".into(),
                present: false,
                evidence: vec![],
            },
            HarnessHit {
                id: "cursor".into(),
                present: true,
                evidence: vec![],
            },
        ];
        assert_eq!(select_ide(&r), "hybrid");
    }

    #[test]
    fn plan_strict_conflicts_errors() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        let mut r = base_report(dir.path());
        r.conflicts = vec![StackConflict {
            kinds: vec!["node".into(), "rust".into()],
            evidence: vec!["Cargo.toml".into(), "package.json".into()],
        }];
        let opts = InstallOptions {
            strict_conflicts: true,
            ..Default::default()
        };
        let err = plan_install(&r, &opts).unwrap_err();
        assert!(matches!(err, CoreError::InvalidInput(_)));
    }

    #[test]
    fn plan_conflicts_warns() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        let mut r = base_report(dir.path());
        r.conflicts = vec![StackConflict {
            kinds: vec!["node".into(), "rust".into()],
            evidence: vec![],
        }];
        let plan = plan_install(&r, &InstallOptions::default()).unwrap();
        assert!(!plan.warnings.is_empty());
    }

    #[test]
    fn install_report_schema_version_1() {
        let r = InstallReport {
            schema_version: 1,
            mode: "install".into(),
            project_root: "/tmp/x".into(),
            steps: vec![],
            created: vec![],
            updated: vec![],
            skipped: vec![],
            backed_up: vec![],
            harnesses_validated: vec![],
            conflicts: vec![],
            warnings: vec![],
            dry_run: false,
        };
        let v = install_report_to_json(&r);
        assert_eq!(v["schemaVersion"], 1);
        assert_eq!(v["mode"], "install");
    }

    fn list_names(dir: &Path) -> Vec<String> {
        let mut v: Vec<String> = fs::read_dir(dir)
            .unwrap()
            .flatten()
            .map(|e| e.file_name().to_string_lossy().to_string())
            .collect();
        v.sort();
        v
    }

    #[test]
    fn apply_dry_run_zero_writes() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        let before = list_names(dir.path());
        let report = install(
            dir.path(),
            &InstallOptions {
                dry_run: true,
                ..Default::default()
            },
        )
        .unwrap();
        assert!(report.dry_run);
        assert_eq!(before, list_names(dir.path()));
    }

    #[test]
    fn apply_creates_config_dare_gitignore() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        let report = install(dir.path(), &InstallOptions::default()).unwrap();
        assert!(!report.dry_run);
        assert!(dir.path().join("dare.config.json").is_file());
        assert!(dir.path().join("DARE/README.md").is_file());
        assert!(dir.path().join(".gitignore").is_file());
        assert!(dir.path().join("dare-graph.yml").is_file());
        assert!(dir.path().join("templates/DESIGN-template.md").is_file());
        assert!(format_install_human(&report).contains("mode: install"));
    }

    #[test]
    fn apply_idempotent_second_run() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        let _ = install(dir.path(), &InstallOptions::default()).unwrap();
        let gi1 = fs::read_to_string(dir.path().join(".gitignore")).unwrap();
        let _ = install(dir.path(), &InstallOptions::default()).unwrap();
        let gi2 = fs::read_to_string(dir.path().join(".gitignore")).unwrap();
        assert_eq!(gi1, gi2);
        assert_eq!(gi1.matches(GITIGNORE_BEGIN).count(), 1);
    }

    #[test]
    fn merge_gitignore_block_stable() {
        let a = merge_gitignore_content("");
        let b = merge_gitignore_content(&a);
        assert_eq!(a, b);
    }

    #[test]
    fn templates_copied_under_templates_dir() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        let _ = install(dir.path(), &InstallOptions::default()).unwrap();
        for t in TEMPLATE_ASSETS {
            assert!(dir.path().join(t).is_file(), "{t}");
        }
    }

    #[test]
    fn graph_created_once() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        let _ = install(dir.path(), &InstallOptions::default()).unwrap();
        let g1 = fs::read_to_string(dir.path().join("dare-graph.yml")).unwrap();
        let _ = install(dir.path(), &InstallOptions::default()).unwrap();
        let g2 = fs::read_to_string(dir.path().join("dare-graph.yml")).unwrap();
        assert_eq!(g1, g2);
    }

    #[test]
    fn ensure_dirs_preserves_existing_execution_files() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        fs::create_dir_all(dir.path().join("DARE/EXECUTION")).unwrap();
        fs::write(dir.path().join("DARE/EXECUTION/keep.md"), "keep").unwrap();
        let _ = install(dir.path(), &InstallOptions::default()).unwrap();
        assert_eq!(
            fs::read_to_string(dir.path().join("DARE/EXECUTION/keep.md")).unwrap(),
            "keep"
        );
    }

    #[test]
    fn rollback_restores_forced_config() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        fs::write(dir.path().join("dare.config.json"), r#"{"ide":"cursor"}"#).unwrap();
        let root = ProjectRoot::new(dir.path()).unwrap();
        let mut journal = SessionJournal::default();
        backup_if_exists(&root, CONFIG_REL, &mut journal).unwrap();
        let p = SafeRelativePath::new(CONFIG_REL).unwrap();
        atomic_write(&root, &p, br#"{"ide":"claude-code"}"#).unwrap();
        rollback(&root, &journal).unwrap();
        let body = fs::read_to_string(dir.path().join("dare.config.json")).unwrap();
        assert!(body.contains("cursor"));
    }

    #[test]
    fn install_full_validates_harnesses() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        let report = install(dir.path(), &InstallOptions::default()).unwrap();
        assert_eq!(
            report.harnesses_validated,
            vec!["antigravity", "claude", "codex", "cursor"]
        );
        for p in DISCOVER_PATHS {
            assert!(dir.path().join(p).is_file(), "{p}");
        }
    }
}
